// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsPonWKBXtpMAuUnQWibRMS4q4Ijl9tVw',
    appId: '1:570946167817:web:3eb85b7782f011ed8e04d8',
    messagingSenderId: '570946167817',
    projectId: 'shoppingapp-2ce57',
    authDomain: 'shoppingapp-2ce57.firebaseapp.com',
    storageBucket: 'shoppingapp-2ce57.firebasestorage.app',
    measurementId: 'G-8X3779HJQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktdTYKLKAjRxjaDIlooXoxEoGvBSyw4w',
    appId: '1:570946167817:android:d274d5650d438b328e04d8',
    messagingSenderId: '570946167817',
    projectId: 'shoppingapp-2ce57',
    storageBucket: 'shoppingapp-2ce57.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2RDd2JBcatPHATnfihvxl5dktz37ZfD4',
    appId: '1:570946167817:ios:7c9d5f9aa92cb1858e04d8',
    messagingSenderId: '570946167817',
    projectId: 'shoppingapp-2ce57',
    storageBucket: 'shoppingapp-2ce57.firebasestorage.app',
    androidClientId: '570946167817-95j9db66rgdlk3uebm56k9pbjptuojdf.apps.googleusercontent.com',
    iosClientId: '570946167817-j4p989g5q0eetcjogd0mkcckdkrf2i59.apps.googleusercontent.com',
    iosBundleId: 'com.harshitvats.grabkrtadmin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2RDd2JBcatPHATnfihvxl5dktz37ZfD4',
    appId: '1:570946167817:ios:423f3d49e2af71488e04d8',
    messagingSenderId: '570946167817',
    projectId: 'shoppingapp-2ce57',
    storageBucket: 'shoppingapp-2ce57.firebasestorage.app',
    androidClientId: '570946167817-95j9db66rgdlk3uebm56k9pbjptuojdf.apps.googleusercontent.com',
    iosClientId: '570946167817-dqkakeq5oiu48lbpvlcbh5mcea4fvcma.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVY93EhL6INr_Th1tjHq8IZvqDWqML2iM',
    appId: '1:570946167817:web:79bfdc81f8ee5e868e04d8',
    messagingSenderId: '570946167817',
    projectId: 'shoppingapp-2ce57',
    authDomain: 'shoppingapp-2ce57.firebaseapp.com',
    storageBucket: 'shoppingapp-2ce57.firebasestorage.app',
    measurementId: 'G-WZWKBSRX78',
  );
}
